name: Release PR
# on: 
#   repository_dispatch:
#     types: [release-published]
# TODO: remove workflow_dispatch this once the go-tableland repository_dispatch is triggering the running of this file
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version of this release. TODO: this should be coming from client client_payload, not inputs"
        required: true
        default: "0.0.0-pre.0"

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update version in package.json
        id: version-bump
        uses: jaywcjlove/github-action-package@v1.3.0
        with:
          path: "./package.json"
          version: ${{ github.event.inputs.release_version }}

      - run: echo "version - ${{ steps.info.outputs.version }}"

      - name: Install 🔧
        run: npm install

      - name: Build 🔧
        run: npm run build

      - uses: actions/github-script@v6
        id: create-release-pr
        name: Create Release PR
        with:
          # use textile.io machine once this file is working
          # github-token: ${{secrets.TEXTILEIO_MACHINE_ACCESS_TOKEN}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              const tag = '${{ github.event.inputs.release_version }}';
              const releaseBranchName = 'refs/heads/release-pr-' + tag;
              const prBody = '✅ This PR was created by the Release PR action for version ' + tag;

              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: releaseBranchName,
                tag: tag,
                sha: baseBranchSHA
              });

              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Release PR ' + tag,
                head: releaseBranchName,
                base: baseBranch,
                body: prBody
              });
            } catch (err) {
              console.log(err);
              core.setFailed('Failed to create release branch: ' + err.message);
              return;
            }
